# Generated by Django 5.0.6 on 2024-05-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_facture_ttc_remove_facture_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureproduct',
            name='TTVA',
            field=models.IntegerField(),
        ),
    ]
