# Generated by Django 5.0.6 on 2024-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_factureproduct_ttva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureproduct',
            name='TTC',
        ),
        migrations.AddField(
            model_name='facture',
            name='TTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
