# Generated by Django 5.0.6 on 2024-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_factureproduct_ttc_facture_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='nemero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
