# Generated by Django 5.0.6 on 2024-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_facture_nemero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.FloatField(),
        ),
    ]
