# Generated by Django 5.0.6 on 2024-05-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_produit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='save_by',
        ),
    ]
