# Generated by Django 5.0.6 on 2024-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_facture_save_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
