# Generated by Django 5.0.6 on 2024-05-30 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_chef_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduct',
            name='Mode_reglement',
            field=models.CharField(choices=[('E', 'ESPACE'), ('C', 'CHEQUE')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
