# Generated by Django 5.0.6 on 2024-05-30 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_factureproduct_mode_reglement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimportant',
            name='name',
        ),
        migrations.AddField(
            model_name='productimportant',
            name='id_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factureproduct',
            name='Mode_reglement',
            field=models.CharField(choices=[('C', 'CHEQUE'), ('E', 'ESPACE')], max_length=1),
        ),
    ]
