# Generated by Django 5.0.6 on 2024-05-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_productimportant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimportant',
            name='id_product',
        ),
    ]
