# Generated by Django 5.0.6 on 2024-05-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_productimportant_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimportant',
            name='id_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.produit'),
            preserve_default=False,
        ),
    ]
