# Generated by Django 5.0.6 on 2024-05-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productimportant_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureproduct',
            name='Mode_reglement',
        ),
        migrations.AddField(
            model_name='facture',
            name='Mode_reglement',
            field=models.CharField(choices=[('E', 'ESPACE'), ('C', 'CHEQUE')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
