# Generated by Django 5.0.6 on 2024-05-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_factureproduct_mode_reglement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='Mode_reglement',
            new_name='ModeReglement',
        ),
    ]
