# Generated by Django 5.0.6 on 2024-05-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_facture_modereglement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='ModeReglement',
            field=models.CharField(choices=[('E', 'ESPACE'), ('C', 'CHEQUE')], max_length=1),
        ),
    ]
