# Generated by Django 5.0.6 on 2024-05-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_facture_modereglement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='ModeReglement',
            new_name='TYPE',
        ),
    ]
