# Generated by Django 5.0.6 on 2024-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_modereglement_facture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Important',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductImportant',
        ),
    ]
