# Generated by Django 5.0.6 on 2024-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_produit_important_delete_productimportant'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureproduct',
            name='Nemero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
