# Generated by Django 5.0.6 on 2024-05-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_factureproduct_nemero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='nemero',
            new_name='Nemero',
        ),
        migrations.RemoveField(
            model_name='factureproduct',
            name='Nemero',
        ),
    ]
